name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2.7 repo liblzma-dev

    - name: Set up build environment
      run: |
        mkdir orangefox
        cd orangefox
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        repo init -u https://gitlab.com/OrangeFox/sync.git -b twrp-7.1
        repo sync -j$(nproc) --force-sync

    - name: Clone device tree
      run: |
        cd orangefox
        git clone https://github.com/124sami/android_device_OPPO_A83.git -b android-7.1 device/OPPO/A83

    - name: Lunch target
      run: |
        cd orangefox
        source build/envsetup.sh
        lunch omni_A83-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v3
      with:
        name: OrangeFox-Recovery
        path: orangefox/out/target/product/A83/recovery.img
