name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: "Enter OrangeFox manifest Git URL"
        required: true
        default: "https://github.com/OrangeFoxRecovery/manifest.git"
      MANIFEST_BRANCH:
        description: "Enter Manifest Branch"
        required: true
        default: "twrp-7.1"
      DEVICE_TREE:
        description: "Enter Device Tree Git URL"
        required: true
        default: "https://github.com/lpxx50117/android_device_OPPO_A83"
      DEVICE_PATH:
        description: "Enter Device Path (device/brand/codename)"
        required: true
        default: "device/OPPO/A83"
      DEVICE_BRANCH:
        description: "Enter Device Tree Branch"
        required: true
        default: "android-7.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up job
      run: echo "Setting up job"

    - name: Check Out
      uses: actions/checkout@v3

    - name: Cleanup
      run: |
        sudo swapoff -a || true
        sudo rm -f /swapfile || true
        sudo apt clean

    - name: Initialize workspace
      id: pwd
      run: echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT

    - name: Prepare the build environment
      run: |
        sudo apt update
        sudo apt install git unzip bc curl repo -y
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        git clone ${{ github.event.inputs.SYNC_URL }} sync_scripts
        cd sync_scripts
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ../fox_${{ github.event.inputs.MANIFEST_BRANCH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone device tree
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        mkdir -p ${{ github.event.inputs.DEVICE_PATH }}
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}

    - name: Clone common tree
      if: ${{ github.event.inputs.COMMON_TREE && github.event.inputs.COMMON_PATH && github.event.inputs.COMMON_BRANCH }}
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        mkdir -p ${{ github.event.inputs.COMMON_PATH }}
        git clone ${{ github.event.inputs.COMMON_TREE }} -b ${{ github.event.inputs.COMMON_BRANCH }} ${{ github.event.inputs.COMMON_PATH }}

    - name: Set Swap Space
      run: |
        sudo fallocate -l 6G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Building recovery
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        source build/envsetup.sh
        lunch omni_A83-eng || lunch twrp_A83-eng
        mka recoveryimage -j$(nproc)

    - name: Check the output directory before uploading
      run: |
        ls -alh ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/*/recovery.img

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Recovery Build for A83"
        tag_name: "orangefox-$(date +'%Y%m%d-%H%M')"
        files: ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/*/recovery.img

    - name: Post Check Out
      run: echo "Done building!"

    - name: Complete job
      run: echo "Workflow complete ✅"
