name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'Manifest Branch (e.g., twrp-7.1, 10.0, 11.0, 12.1)'
        required: true
        default: 'twrp-7.1' # Set default to the correct branch for your device
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/lpxx50117/android_device_OPPO_A83' # Set default to your device tree
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'android-7.1' # Set default to your device tree branch
      DEVICE_PATH:
        description: 'Device Path (e.g., device/xiaomi/mido)'
        required: true
        default: 'device/OPPO/A83' # Set default to your device path
      COMMON_TREE_URL:
        description: 'Common Tree URL (if no common tree, leave blank)'
        required: false
        default: ''
      COMMON_PATH:
        description: 'Common Path (if no common tree, leave blank)'
        required: false
        default: ''
      DEVICE_NAME:
        description: 'Device Name (e.g., mido)'
        required: true
        default: 'A83' # Set default to your device name
      MAKEFILE_NAME:
        description: 'Makefile Name (e.g., twrp_mido, orangefox_gardon)'
        required: true
        default: 'twrp_cph1729' # Set default to your specific makefile name
      BUILD_TARGET:
        description: 'Build Target (e.g., recovery)'
        required: true
        default: 'recovery'

jobs:
  build:
    runs-on: ubuntu-22.04 # Changed from ubuntu-latest or ubuntu-20.04 to the supported LTS version

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib \
          libc6-dev-i386 lib32z1 lib32stdc++6 lib32gcc-s1 \
          libncurses5-dev libx11-dev libxml2-utils xsltproc unzip \
          lzop pngcrush bc rsync imagemagick \
          squashfs-tools schedtool liblz4-tool libssl-dev wget patch

    - name: Install repo tool and set PATH
      run: |
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Initialize repo and sync # Renamed for clarity, removed fox_9.0 specific steps
      run: |
        mkdir -p ~/orangefox && cd ~/orangefox
        git config --global user.name "builder"
        git config --global user.email "builder@localhost"
        # Initialize repo with the correct TWRP 7.1 manifest
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b ${{ github.event.inputs.MANIFEST_BRANCH }} --depth=1
        # Sync the repositories
        repo sync -j$(nproc) --force-sync

    - name: Clone device tree
      run: |
        cd ~/orangefox
        # Use the input variables directly here
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }}.git -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}

    - name: Setup and build recovery
      run: |
        cd ~/orangefox
        source build/envsetup.sh
        # Use the input variables for lunch and mka
        lunch omni_${{ github.event.inputs.DEVICE_NAME }}-eng
        mka ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc)

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: recovery.img
        path: ~/orangefox/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
