name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Set up job
      run: echo "Starting build..."

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex git \
          gnupg gperf libncurses5-dev libssl-dev libxml2-utils lzop \
          pngcrush rsync schedtool squashfs-tools xsltproc zip \
          lib32z1 lib32ncurses5-dev lib32readline-dev lib32stdc++6 \
          python-is-python3 git wget unzip

    - name: Set up repo
      run: |
        mkdir ~/fox && cd ~/fox
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Clone sync scripts
      run: |
        cd ~/fox
        git clone https://github.com/OrangeFoxRecovery/manifest.git -b sync_scripts sync_scripts

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        cd ~/fox/sync_scripts
        ./orangefox_sync.sh --branch twrp-7.1 --path ../fox_twrp-7.1

    - name: Clone device tree
      run: |
        cd ~/fox/fox_twrp-7.1
        git clone https://github.com/124sami/device_oppo_a83 device/oppo/a83

    - name: Clone common tree
      run: |
        cd ~/fox/fox_twrp-7.1/device/oppo/a83
        git clone https://github.com/124sami/android_device_oppo_mt6763-common -b ofrp ../../../oppo/mt6763-common

    - name: Set swap space
      run: |
        sudo fallocate -l 3G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Build recovery
      run: |
        cd ~/fox/fox_twrp-7.1
        source build/envsetup.sh
        lunch omni_a83-eng
        mka recoveryimage

    - name: Check the output directory before uploading
      run: ls -al ~/fox/fox_twrp-7.1/out/target/product/a83

    - name: Upload to Release
      uses: actions/upload-artifact@v3
      with:
        name: OrangeFox-Recovery
        path: ~/fox/fox_twrp-7.1/out/target/product/a83/recovery.img

    - name: Post job cleanup
      run: echo "Build finished."
      
