name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Set up job
      uses: actions/checkout@v3

    - name: Clean up
      run: |
        sudo swapoff -a || true
        sudo rm -f /swapfile || true

    - name: Initialize workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/fox_twrp-7.1

    - name: Prepare the build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev \
            lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-8-jdk \
            pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev ccache python-is-python3

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/OrangeFoxRecovery/manifest.git sync_scripts
        cd sync_scripts
        ./orangefox_sync.sh --branch twrp-7.1 --path ../fox_twrp-7.1

    - name: Clone device tree
      run: |
        cd $GITHUB_WORKSPACE/fox_twrp-7.1
        mkdir -p device/OPPO/A83
        git clone https://github.com/lpxx50117/android_device_OPPO_A83 -b android-7.1 device/OPPO/A83

    - name: Clone common tree
      run: |
        cd $GITHUB_WORKSPACE/fox_twrp-7.1
        mkdir -p device/mediatek/sepolicy_vndr
        git clone https://github.com/TeamWin/android_device_mediatek_sepolicy_vndr -b android-7.1 device/mediatek/sepolicy_vndr

    - name: Set Swap Space
      run: |
        sudo fallocate -l 6G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Building recovery
      run: |
        cd $GITHUB_WORKSPACE/fox_twrp-7.1
        . build/envsetup.sh
        lunch omni_A83-eng
        mka recoveryimage

    - name: Check the output directory before uploading
      run: |
        ls -lh $GITHUB_WORKSPACE/fox_twrp-7.1/out/target/product/*

    - name: Upload to Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.workspace }}/fox_twrp-7.1/out/target/product/*/recovery.img
        tag: "latest"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}

