name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib \
          libc6-dev-i386 lib32z1 lib32stdc++6 lib32gcc-s1 \
          libncurses5-dev libx11-dev libxml2-utils xsltproc unzip \
          lzop pngcrush bc rsync imagemagick \
          squashfs-tools schedtool liblz4-tool libssl-dev wget

        # Manually install Python 2.7
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar -xzf Python-2.7.18.tgz
        cd Python-2.7.18
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall
        cd ..
        sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python

    - name: Initialize repo and sync source
      run: |
        mkdir -p ~/orangefox
